#!/bin/bash

# Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file.

cat /etc/passwd | cut -d: -f1,3,7

# https://unix.stackexchange.com/questions/101424/print-some-fields-of-etc-passwd
# https://www.cyberciti.biz/faq/understanding-etcpasswd-file-format/
